name: "Publish Release"

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'tag is going to be released'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Cache Bedrock Dedicated Server Library
        id: cache-bds-lib
        uses: actions/cache@v3
        env:
          cache-name: cache-bds-lib
        with:
          path: |
            ${{ env.GITHUB_WORKSPACE }}LiteLoader/Lib/bedrock_server_api.lib
            ${{ env.GITHUB_WORKSPACE }}LiteLoader/Lib/bedrock_server_var.lib
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/LINK.txt') }}

      - name: Download Server
        if: steps.cache-bds-lib.outputs.cache-hit != 'true'
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          mkdir Tools/Server
          ServerLink=$(cat 'scripts/LINK.txt')
          curl -L -o Tools/Server/server.zip "$ServerLink"
          unzip Tools/Server/server.zip -d Tools/Server/ > /dev/null
        shell: bash

      - name: Build Library
        if: steps.cache-bds-lib.outputs.cache-hit != 'true'
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          cd Tools
          LibraryBuilder.exe Server
          mkdir ..\LiteLoader\lib
          move bedrock_server_api.lib ..\LiteLoader\lib
          move bedrock_server_var.lib ..\LiteLoader\lib
        shell: cmd

      - name: Change LITELOADER_VERSION_STATUS_BETA
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        if: github.ref == 'refs/heads/beta'
        run: |
          sed -r -i 's/#define\s+LITELOADER_VERSION_STATUS\s+LITELOADER_VERSION_\w+/#define LITELOADER_VERSION_STATUS   LITELOADER_VERSION_BETA/' LiteLoader/include/liteloader/Version.h
          sed -r -i 's/#define\s+LITELOADER_VERSION_ACTIONS\s+.*/#define LITELOADER_VERSION_ACTIONS  ${{ github.run_number }}\r/' LiteLoader/include/liteloader/Version.h
          cat LiteLoader/include/liteloader/Version.h
        shell: bash

      - name: Change LITELOADER_VERSION_STATUS_RELEASE
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        if: github.ref == 'refs/heads/main'
        run: |
          sed -r -i 's/#define\s+LITELOADER_VERSION_STATUS\s+LITELOADER_VERSION_\w+/#define LITELOADER_VERSION_STATUS   LITELOADER_VERSION_RELEASE/' LiteLoader/include/liteloader/Version.h
          sed -r -i 's/#define\s+LITELOADER_VERSION_ACTIONS\s+.*/#define LITELOADER_VERSION_ACTIONS  ${{ github.run_number }}\r/' LiteLoader/include/liteloader/Version.h
        shell: bash

      - name: Get MSVC Path
        working-directory: E:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\
        run: echo "MSVC_VER=$(ls | tail -n 1)" >> $GITHUB_ENV
        shell: bash

      - name: Configure CMake(MSVC)
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: cmd

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        shell: cmd

      - name: Pack output and SDK
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target PackOutput
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target PackSDK
        shell: cmd

      - name: Compress Resource Packs
        run: |
          cd build/output/plugins/LiteLoader/ResourcePacks
          7z a LiteLoaderBDS-CUI.tar LiteLoaderBDS-CUI
          rm -r LiteLoaderBDS-CUI
        shell: bash

      - name: Pack PDB for Release
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: 7z a -tzip PDB.zip build/pdb
        shell: bash

      - name: Pack Release
        working-directory: ${{ github.workspace }}/build/output
        id: rel
        run: |
          7z a -y -tzip -mmt -mx=9 ../../LiteLoader-${{ github.event.inputs.tag }}.zip *
        shell: bash

      - name: Create New Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          tag_name: ${{ github.event.inputs.tag }}
          body_path: ${{ github.workspace }}\CHANGELOG.md
          files: |
            ${{ github.workspace }}\LiteLoader-${{ github.event.inputs.tag }}.zip
            ${{ github.workspace }}\PDB.zip
        env:
          GITHUB_REPOSITORY: LiteLDev/LiteLoaderBDS
